version: "3.8"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinicdb
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: clinic_pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: clinic_user
      DB_PASSWORD: clinic_pass
      DB_NAME: clinicdb
      JWT_SECRET: supersecret
      JWT_EXPIRES_IN: 7d
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8000:80"
